apiVersion: apps/v1
kind: Deployment
metadata:
  name: netgen-deployment
  labels:
    app: my-helloword
    tier: frontend
    
spec:
  replicas: 2
  selector: 
    matchLabels:
     app: myapp 
  template: 
    metadata:
      name: myapp-pod 
      labels: # DICTIONARY
        app: myapp
    spec:
      containers: 
        - name: myapp 
          image: nformiblandine/nformiblandine:latest
          ports: 
            - containerPort: 80
